# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f2119a0f716b174fb77d3c7fe46e859"
application_url = "https://copper-shaped-webcams-push.trycloudflare.com"
embedded = true
name = "oct-21"
handle = "oct-31"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "isaac-may-2023.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_purchase_options"

[auth]
redirect_urls = [
  "https://copper-shaped-webcams-push.trycloudflare.com/auth/callback",
  "https://copper-shaped-webcams-push.trycloudflare.com/auth/shopify/callback",
  "https://copper-shaped-webcams-push.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
