# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37f992e4e2433b2628c81ac2860dbb8e"
application_url = "https://tuesday-cuba-reaches-available.trycloudflare.com"
embedded = true
name = "oct-18"
handle = "oct-30"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "isaac-may-2023.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tuesday-cuba-reaches-available.trycloudflare.com/auth/callback",
  "https://tuesday-cuba-reaches-available.trycloudflare.com/auth/shopify/callback",
  "https://tuesday-cuba-reaches-available.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
